### PR TITLE
Add functionality to provide information

### PR DESCRIPTION
**Pull request by Dongyeon1201**
First of all, thank you for creating such a great tool :)
While using it personally, I thought it would be nice if information about the changed lines was provided as well, so I added this feature.

Thank you :)

[ Change Info ]
- Add functionality to provide information
- Applied dataclass to the `DiffBlock` class
- Modified README

### CODE REVIEW

**Comment by shaiksamad** [comment]
Thankyou for your contribution. 

That info is called "Hunk Header". 

I feel like variable names are confusing. `old` and `new` are not clear. instead `original` and `modified` would be nice and more  accurate. What do you think?

**Comment by Dongyeon1201** [comment]
@shaiksamad 
As you suggested, I have renamed the variable :)
Please check [commit](https://github.com/shaiksamad/diff-parser/pull/2/commits/f7fe8f331ce1cd387d26e23b8e7944aa7c37efbf).

Thank you.

**Comment by Dongyeon1201** [comment]
@shaiksamad 
After leaving the comment, I realized I hadn’t applied the changes to the README, so I have updated it as well.
Please take a look :)

[commit](https://github.com/shaiksamad/diff-parser/pull/2/commits/29808ddb026d8e42366d82faaee90ffcf14f4b8d)

**Comment by shaiksamad** [comment]
Can you implement `file_mode`.

`file_mode` is a number at the end of the second line (index line);  for example: 100644

**Comment by Dongyeon1201** [comment]
@shaiksamad 
It seems perfectly feasible using regular expressions (re).
However, I believe it would be better to manage the history by creating a separate issue and PR for the feature you mentioned. What do you think?

**Comment by shaiksamad** [comment]
Ok let me merge this

**Comment by shaiksamad** [comment]
I created a new [issue](https://github.com/shaiksamad/diff-parser/issues/3#issue-2544316636) for implementing `file_mode`

**Pull request merged**
